---
title: "R Day 2"
author: "Elliot Gardner"
date: "9/18/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
here::here("data","gapminder5.csv")

gapminder <- read.csv(here::here("data","gapminder5.csv"))
```

## converting factors to characters

```{r}
gapminder$country <- as.character(gapminder$country)
gapminder$continent <- as.character(gapminder$continent)
str(gapminder)
```

## computing the GDP for each country

```{r}
# create a vector of values that you want to repeat the function for
obs <- 1:nrow(gapminder)

# initialize the for loop with `for (i in vector)`
for (i in obs) { #the function to repeat is enclosed in braces {}
  gapminder[i, "gdp"] <- gapminder[i, "pop"] * gapminder[i, "gdpPercap"]
}
head(gapminder)
```

## computing the log of the GDPperCapita and the population

```{r}
#creating the log of GDPperCapita
for (i in obs) {
  gapminder[i, "log_gdpPercap"] <- log(gapminder[i, "gdpPercap"])
  gapminder[i, "log_pop"] <- log(gapminder[i, "pop"])
}
head(gapminder)

gapminder$vec_log_gdpPercap <- log(gapminder$gdpPercap)
all(gapminder$vec_log_gdpPercap == gapminder$log_gdpPercap)
```

## looking at life expectancy by year and by continent

```{r}
#creating unique year data
years <- unique(gapminder$year)

for (i in years){
  mean_le <- mean(gapminder$lifeExp[gapminder$year == i], na.rm = TRUE)
  print(paste0(i, ":", mean_le))
}

continents <- unique(gapminder$continent)

for (i in continents){
  mean_le_con <- mean(gapminder$lifeExp[gapminder$continent == i], na.rm = TRUE)
  print(paste0(i, ":", mean_le_con))
}

for(i in continents){
  print(paste0("Continent: ",i))
  for (j in years) {
    mean_le_con_yr <- mean(gapminder$lifeExp[gapminder$continent == i & gapminder$year == j], na.rm = TRUE)
    print(paste0(j, ":", mean_le_con_yr))
  }
}

for (i in continents){
  print(paste0("Continent: ",i))
  for (j in years){
    std_dev_le <- sd(gapminder$lifeExp[gapminder$continent == i & gapminder$year == j])
    print(paste0(j,":",std_dev_le))
  }
}
```

## apply, lapply, sapply

```{r}
vars <- gapminder[, c("lifeExp","pop","gdpPercap")] #numeric only data frame
apply(vars, 2, mean) #2 means that we are applying over columns, 1 would be over rows

for(i in vars){
  print(mean(i))
}

lapply(gapminder, mean)

sapply(gapminder, mean)

sapply(years, function(x) mean(gapminder$lifeExp[gapminder$year == x]))
```

## while loops

```{r}
i <- 1952 #initialize the iterator value

while (i < 1987) {
  sd_le <- sd(gapminder$lifeExp[gapminder$year == i])
  print(paste0(i, ": ", sd_le))
  
  i <- i + 5 #increment the iterator
  
}

i <- 1987

while (i <= 2002) {
  sd_le <- sd(gapminder$lifeExp[gapminder$year == i])
  print(paste0(i, ":", sd_le))
  
  i <- i + 5
}
```

## if/else statements

```{r}
random_year <- sample(years, 1)

if (random_year > 1987) {
  print(random_year)
} else{
  print("It was before you were born!")
}

threshold <- 70

for (i in unique(gapminder$continent)) {
  tmp <- mean(gapminder$lifeExp[gapminder$continent==i])
  
  if(tmp < threshold){
    print(paste("Mean Life Expectancy in", i, "is less than",threshold))
  } else {
    print(paste("Mean Life Expectancy in", i, "is more than",threshold))
    }
  
}

year_limit <- 1987

for (i in years) {
  tmp <- mean(gapminder$pop[gapminder$year == i])
  
  if(i<year_limit){
    print("Too early!")
  } else{
    print(paste0("Mean Population in ",i," was ",tmp))
  }
}
```

## functions

```{r}
get_values <-
  function(df, variable = "continent") {
    vals <- unique(df[[variable]]) #use double brackets to identify the column with a variable, the dollar sign won't accept a variable afterwards
    print(paste0(variable, ": ", vals))
  }

get_values(gapminder)

report_mean_sd <-
  function(df, variable, country) {
    var <- df[[variable]][df$country == country]
    m_le <- mean(var)
    sd_le <- sd(var)
    cat("Country:", country, "\nMean Life Expectancy:", m_le, "\nSD Life Expectancy:", sd_le,"\n")
  }

report_mean_sd(gapminder, "lifeExp", "Bulgaria")

report_stats <-
  function(df, var, cont) {
    vars <- df[[var]][df$continent == cont]
    mean_le <- mean(vars)
    median_le <- median(vars)
    max_le <- max(vars)
    min_le <- min(vars)
    
    cat("Continent:", cont, "\nMean LE:", mean_le, "\nMedian LE:",median_le,"\nMax LE:",max_le,"\nMin LE",min_le,"\n")
  }

report_stats(gapminder, "pop", "Europe")
```

## functions and loops

```{r}
viz_lm <-
  function(df, dv, iv, year) {
    dat <- df[df[["year"]] == year, ]
    y <- log(dat[[dv]])
    x <- log(dat[[iv]])
    
    fit <- lm(y~x)
    
    plot(y~x, main = year, xlab = iv, ylab = dv)
    lines(x, predict(fit), col = 'blue')
  }
for (i in years) {
  viz_lm(gapminder, "lifeExp", "gdpPercap", i)
}

```